import type { SiteContent } from "./types";
import { storyChaptersEn } from "./story";

export const en: SiteContent = {
  meta: {
    title: "Fernando Urbano - AI without bluff",
    description:
      "Director of Innovation at Rocketbot. Writing about applied AI for business across LATAM. 200+ clients advised. 40 Under 40 Innovators 2024.",
  },
  nav: [
    { segment: "historia", label: "Story", number: "01" },
    { segment: "que-hago", label: "What I do", number: "02" },
    { segment: "charlas", label: "Talks", number: "03" },
    { segment: "ideas", label: "Ideas", number: "04" },
    { segment: "prensa", label: "Press", number: "05" },
    { segment: "contacto", label: "Contact", number: "06" },
  ],
  ctas: {
    speakerSubtle: "For keynotes, panels and media",
    speakerLong: "Keynotes, panels, in-company training and media",
    contact: "Write me",
    pressKit: "Download press kit",
    work: "How we can work together",
    readMore: "Keep reading",
    seeAll: "See all",
    sendTelegram: "Send telegram",
    watch: "Watch",
    filterAll: "All",
  },
  ui: {
    now: "Now",
    in: "In",
    based: "Based in",
    next: "Next",
    featured: "Featured in",
    selectedTalks: "Selected talks",
    selectedIdeas: "Recent ideas",
    selectedPress: "Recognition",
    fromUruguayTo: "From Uruguay across the continent",
    languageShort: "EN",
    plate: "Plate",
    auto: "auto",
    paused: "paused",
    currentlyWriting: "Currently writing",
    comingSoon: "Coming soon",
    chooseIntent: "Choose an option to continue",
    yourName: "Your name",
    organization: "Organization",
    context: "Context",
    yourEmail: "Your email",
    replyBy: "Reply deadline (optional)",
    mailFallback: "Email client didn't open? Copy this:",
  },
  home: {
    eyebrow: "Applied AI · Strategy · LATAM × Iberia",
    manifesto: { lead: "I talk about AI", tail: "because I build it." },
    trip: {
      nowLabel: "Now",
      nextLabel: "Next",
      now: { city: "Montevideo", country: "Uruguay", countryCode: "uy" },
      next: { city: "Santiago", country: "Chile", countryCode: "cl", when: "Jun 2026" },
    },
    intro:
      "I'm Director of Innovation at Rocketbot. I lead agentic product, applied AI and operational efficiency. I've advised 200+ clients across seven countries and was named 40 Under 40 Innovators Global in 2024.",
    bioOneLine:
      "Builder of agentic product. Writing about applied AI for business across LATAM.",
    nowStatus:
      "Leading the agent roadmap at Rocketbot. Writing here about what I learn while building applied AI.",
    stats: [
      { value: "200+", label: "Clients advised" },
      { value: "7", label: "Countries with talks" },
      { value: "3", label: "Global awards 2016-18" },
      { value: "40<40", label: "Innovators 2024" },
    ],
    sections: [
      { number: "01", title: "Story", blurb: "From Ciudad de la Costa to the world. 11 chapters.", href: "/en/historia" },
      { number: "02", title: "What I do", blurb: "The areas I work in and know deepest.", href: "/en/que-hago" },
      { number: "03", title: "Talks", blurb: "Keynotes, Agentic Tour and RPA Day.", href: "/en/charlas" },
      { number: "04", title: "Ideas", blurb: "Unfiltered essays on AI and business.", href: "/en/ideas" },
      { number: "05", title: "Press", blurb: "Awards and media mentions.", href: "/en/prensa" },
    ],
    quote: {
      text: "Eighty percent of the AI pilots I see die because of bad strategy. Not bad technology.",
      attribution: "Fernando Urbano, RPA Day Spain",
    },
    speakerPull: {
      eyebrow: "Booking & media",
      title: "If you need someone who talks about AI with facts, not fog.",
      blurb:
        "Keynotes, panels, in-company training, innovation juries, interviews on TV, radio and podcast.",
    },
  },
  story: {
    eyebrow: "The road",
    title: "11 chapters. 29 years. One road.",
    intro:
      "I don't come from theory. I come from shipping, selling, breaking, fixing and selling again.",
    lead:
      "Born in Ciudad de la Costa in 1997, son of Daniel and Mariela. Curiosity was the fuel from day one.",
    stats: [
      { value: "11", label: "Chapters" },
      { value: "6", label: "Companies" },
      { value: "7", label: "Countries" },
      { value: "1", label: "Obsession" },
    ],
    chapters: storyChaptersEn,
    footerCta: { label: "What I do today", href: "/en/que-hago" },
  },
  services: {
    eyebrow: "What I work on",
    title: "Agentic product, automation and applied AI.",
    intro:
      "I work in RPA, hyperautomation, AI systems, LLMs and business agents across LATAM and Iberia. I write about what I build, not about what I read.",
    lanes: [
      {
        number: "01",
        title: "Agentic product",
        blurb:
          "I lead the business-agent roadmap at Rocketbot: design, architecture and production rollout of systems that do real work.",
        engagements: ["Business agents", "Multi-agent", "Applied AI", "Product roadmap"],
        stat: { value: "2", label: "Years leading agents" },
      },
      {
        number: "02",
        title: "Automation",
        blurb:
          "Over a decade in RPA and hyperautomation: 80+ processes automated across 12 countries. From bots to agents, with business judgment.",
        engagements: ["RPA", "Hyperautomation", "Orchestration", "Processes"],
        stat: { value: "80+", label: "Processes automated" },
      },
      {
        number: "03",
        title: "Anti-bluff judgment",
        blurb:
          "I separate what AI will actually do from what is fog. Facts, cases and numbers, not LinkedIn promises. That's what I try to put in writing here.",
        engagements: ["Strategy", "LLMs in production", "Cost and latency", "Risk"],
        stat: { value: "40<40", label: "Innovators Global 2024" },
      },
    ],
    expertiseTitle: "Expertise spectrum",
    expertiseIntro: "Depth accumulated in the field, not in slides.",
    expertise: [
      { id: "rpa", name: "RPA", level: 5, years: 8, caption: "80+ processes automated in 12 countries, Ricoh LATAM" },
      { id: "hyper", name: "Hyperautomation", level: 5, years: 6, caption: "Practia / Publicis Sapient, banking and retail" },
      { id: "ai-sys", name: "AI systems", level: 4, years: 4, caption: "Architecture and production deployment" },
      { id: "llm", name: "LLMs", level: 4, years: 3, caption: "Selection, cost, latency and risk" },
      { id: "agents", name: "Business agents", level: 5, years: 2, caption: "Agentic product, Rocketbot" },
      { id: "multi", name: "Multi-agent systems", level: 4, years: 2, caption: "Global agentic roadmap" },
    ],
    useCasesTitle: "Topics I obsess over",
    useCases: [
      { number: "01", title: "AI portfolios that collapse", blurb: "What to cancel, accelerate and actually measure." },
      { number: "02", title: "Applied AI without fog", blurb: "What actually works in LATAM, with real cases." },
      { number: "03", title: "Agents in production", blurb: "From eternal pilot to production in 8 weeks." },
      { number: "04", title: "LLMs with judgment", blurb: "Cost, latency and risk before hype." },
    ],
    ctaTalks: "See talks",
    ctaContact: "Read the ideas",
  },
  speaking: {
    eyebrow: "On Tour",
    title: "Live. 7 countries. 1 message.",
    intro:
      "Keynotes, webinars, training and executive breakfasts. Applied AI for business: what works, what doesn't, and why.",
    stats: [
      { value: "10+", label: "Years on stage" },
      { value: "15+", label: "Cities" },
      { value: "7", label: "Countries 2026" },
      { value: "1", label: "Message" },
    ],
    agenticTour: {
      eyebrow: "Latest · 2026",
      title: "Agentic Tour 2026",
      blurb:
        "Training, keynotes and executive breakfasts in seven countries. The message: business agents in production, not eternal pilots.",
      stops: [
        { countryCode: "ar", city: "Buenos Aires", country: "Argentina", format: "Keynote + training" },
        { countryCode: "cl", city: "Santiago", country: "Chile", format: "Executive breakfast" },
        { countryCode: "py", city: "Asunción", country: "Paraguay", format: "Training" },
        { countryCode: "mx", city: "Mexico City", country: "Mexico", format: "Keynote" },
        { countryCode: "co", city: "Bogotá", country: "Colombia", format: "Executive breakfast" },
        { countryCode: "pe", city: "Lima", country: "Peru", format: "Training" },
        { countryCode: "uy", city: "Montevideo", country: "Uruguay", format: "Keynote" },
      ],
    },
    formats: [
      { name: "Keynote", description: "30 to 45 minutes. Conferences and large events." },
      { name: "Panel", description: "60 to 90 minutes. Conversation with moderator." },
      { name: "Workshop", description: "Half day to 3 days. In-company." },
      { name: "Executive breakfast", description: "90 minutes. C-level and boards." },
      { name: "Webinar", description: "60 minutes. Regional live audience." },
    ],
    topics: [
      "Applied AI for business in LATAM",
      "Business agents: minimum viable architecture",
      "Why AI pilots die in production",
      "RPA and hyperautomation: from 80 processes to agents",
      "LLMs in production: cost, latency and risk",
      "Anti-bluff: evaluating an AI initiative in 20 minutes",
    ],
    filterLabels: {
      all: "All",
      Keynote: "Keynote",
      Panel: "Panel",
      Workshop: "Workshop",
      "Charla magistral": "Lecture",
      "Desayuno corporativo": "Breakfast",
      Webinar: "Webinar",
      Capacitacion: "Training",
    },
    events: [
      { year: "2026", title: "Agentic Tour · Uruguay", venue: "Agentic Tour 2026", city: "Montevideo", country: "Uruguay", countryCode: "uy", format: "Keynote", featured: true },
      { year: "2026", title: "Agentic Tour · Chile", venue: "Agentic Tour 2026", city: "Santiago", country: "Chile", countryCode: "cl", format: "Desayuno corporativo", featured: true },
      { year: "2026", title: "Agentic Tour · Argentina", venue: "Agentic Tour 2026", city: "Buenos Aires", country: "Argentina", countryCode: "ar", format: "Keynote", featured: true },
      { year: "2026", title: "Agentic Tour · Mexico", venue: "Agentic Tour 2026", city: "Mexico City", country: "Mexico", countryCode: "mx", format: "Keynote", featured: true },
      { year: "2026", title: "Agentic Tour · Colombia", venue: "Agentic Tour 2026", city: "Bogotá", country: "Colombia", countryCode: "co", format: "Desayuno corporativo", featured: true },
      { year: "2026", title: "Agentic Tour · Peru", venue: "Agentic Tour 2026", city: "Lima", country: "Peru", countryCode: "pe", format: "Capacitacion", featured: true },
      { year: "2026", title: "Agentic Tour · Paraguay", venue: "Agentic Tour 2026", city: "Asunción", country: "Paraguay", countryCode: "py", format: "Capacitacion", featured: true },
      { year: "2025", title: "Official webinar · AI agent development", venue: "Rocketbot", city: "Regional", country: "LATAM", countryCode: "world", format: "Webinar", featured: true },
      { year: "2025", title: "RPA Day Spain", venue: "RPA Day", city: "Madrid", country: "Spain", countryCode: "es", format: "Keynote", featured: true },
      { year: "2024", title: "Lecture · ORT", venue: "Universidad ORT", city: "Montevideo", country: "Uruguay", countryCode: "uy", format: "Charla magistral" },
      { year: "2023", title: "Lecture · UnoChapecó", venue: "UnoChapecó", city: "Chapecó", country: "Brazil", countryCode: "br", format: "Charla magistral" },
    ],
  },
  ideas: {
    eyebrow: "Ideas",
    title: "What I think, no filter.",
    intro:
      "Essays, takes and cases. If you only read one thing this week, make it something that changes how you decide on Monday.",
    currentlyWriting: {
      title: "Multi-agent systems in production",
      status: "Draft in progress",
      eta: "Jun 2026",
    },
    newsletter: {
      label: "One idea per week, no spam",
      href: "mailto:hola@fernandourbano.ai?subject=Newsletter",
    },
    pillars: [
      {
        number: "01",
        volume: "01",
        issue: "01",
        kicker: "Strategy",
        title: "What AI will actually do in LATAM (and what is fog)",
        lead: "Five things worth investing capital in. Three that will make you lose it.",
        blurb: "With real examples from the last 18 months in banking, retail and telcos.",
        readingTime: "11 min",
        tags: ["LATAM", "Strategy", "Capital"],
        slug: "ia-en-latam-y-lo-que-es-humo",
      },
      {
        number: "02",
        volume: "01",
        issue: "02",
        kicker: "Operations",
        title: "Why 80% of AI pilots die in production",
        lead: "An honest autopsy. Spoiler: it's almost never the model.",
        blurb: "Almost always the process, dirty data and missing owner.",
        readingTime: "9 min",
        tags: ["Production", "RPA", "Process"],
        slug: "por-que-mueren-los-pilotos-de-ia",
      },
      {
        number: "03",
        volume: "01",
        issue: "03",
        kicker: "Architecture",
        title: "Agents that actually ship: minimum viable architecture",
        lead: "Eight weeks to production. Stack, decisions and trade-offs.",
        blurb: "How to build a business agent that pays for itself.",
        readingTime: "14 min",
        tags: ["Agents", "Architecture", "MVP"],
        slug: "agentes-que-si-venden-arquitectura-minima-viable",
      },
    ],
  },
  press: {
    eyebrow: "Recognition",
    title: "4 awards. 12 years. And a conversation just starting.",
    intro:
      "Innovation awards, media mentions and presence on the accounts of brands moving automation in LATAM.",
    awards: [
      { year: "2016", outlet: "24 Horas de Innovación", title: "Global innovation award", description: "First international recognition for applied innovation. Work crossed oceans before I did." },
      { year: "2017", outlet: "Rally de Innovación", title: "Second consecutive award", description: "Confirmation it wasn't luck: two years selected among global projects." },
      { year: "2018", outlet: "CampusParty", title: "Third consecutive global award", description: "CampusParty as stage. Three consecutive years of international innovation recognition." },
      { year: "2024", outlet: "40 Under 40 Innovators Global", title: "Global selection", description: "Fewer than 40 people worldwide for applied innovation. Road confirmed beyond the region." },
    ],
    mentionsTitle: "Media and social mentions",
    mentionsIntro: "Videos and appearances on official accounts of reference automation brands, 2025-2026.",
    mentions: [
      { year: "2026", outlet: "Rocketbot Official", title: "Agentic Tour 2026 · highlights", kind: "social", thumbnailSrc: "/mentions/placeholders/01.svg" },
      { year: "2025", outlet: "Rocketbot Official", title: "AI agents webinar · regional", kind: "social", thumbnailSrc: "/mentions/placeholders/02.svg" },
      { year: "2025", outlet: "RPA Day Spain", title: "RPA Day 2025 keynote", kind: "social", thumbnailSrc: "/mentions/placeholders/03.svg" },
      { year: "2025", outlet: "UiPath Community LATAM", title: "RPA community mention", kind: "social", thumbnailSrc: "/mentions/placeholders/04.svg" },
    ],
    pressKitBlurb:
      "Short, medium and long bio in Spanish and English, editorial portraits, topic list, formats and credentials. Direct PDF download.",
  },
  contact: {
    eyebrow: "Contact",
    title: "Got something to tell me? Write.",
    intro:
      "I read everything. To comment on an idea, push back on something I wrote, or just say hi, email is the best channel.",
    intents: [
      { id: "keynote", label: "Keynote or panel", helper: "Conference, congress, private event.", placeholder: "Estimated audience, format, tentative date, city and topic of interest.", emailSubject: "Keynote / panel inquiry" },
      { id: "advisory", label: "Advisory", helper: "Board advisor, committee, strategic session.", placeholder: "Company, role you're looking for, time horizon and concrete problem.", emailSubject: "Advisory inquiry" },
      { id: "training", label: "In-company training", helper: "Executive or technical workshop.", placeholder: "Team size, technical level, desired duration and workshop goal.", emailSubject: "In-company training inquiry" },
      { id: "media", label: "Media", helper: "Interview, column, podcast, TV or radio.", placeholder: "Outlet, format, audience and publication or recording date.", emailSubject: "Media inquiry" },
    ],
    form: {
      submit: "Send telegram",
      nameLabel: "Your name",
      orgLabel: "Organization",
      contextLabel: "Context",
      emailLabel: "Your email",
      deadlineLabel: "Reply deadline (optional)",
    },
    methods: [
      { kind: "Email", label: "Direct email", value: "hola@fernandourbano.ai", href: "mailto:hola@fernandourbano.ai" },
      { kind: "LinkedIn", label: "LinkedIn", value: "/in/f-urcastro", href: "https://www.linkedin.com/in/f-urcastro/" },
    ],
  },
  footer: {
    sloganLine1: "AI without bluff.",
    sloganLine2: "Business at velocity.",
    rights: "All rights reserved",
    ticker: [
      "Director of Innovation · Rocketbot",
      "40 Under 40 Innovators Global 2024",
      "200+ clients advised",
      "RPA and hyperautomation since 2016",
      "Global innovation awards 2016 · 2017 · 2018",
      "I write about applied AI for business.",
    ],
  },
};
