import type { SiteContent } from "./types";
import { storyChaptersEs } from "./story";

export const es: SiteContent = {
  meta: {
    title: "Fernando Urbano - IA sin bluff",
    description:
      "Director de Innovación en Rocketbot. Escribo sobre IA aplicada al negocio en LATAM. 200+ clientes asesorados. 40 Under 40 Innovators 2024.",
  },
  nav: [
    { segment: "historia", label: "Historia", number: "01" },
    { segment: "que-hago", label: "Qué hago", number: "02" },
    { segment: "charlas", label: "Charlas", number: "03" },
    { segment: "ideas", label: "Ideas", number: "04" },
    { segment: "posts", label: "Posts", number: "05" },
    { segment: "prensa", label: "Prensa", number: "06" },
    { segment: "contacto", label: "Contacto", number: "07" },
  ],
  ctas: {
    speakerSubtle: "Para conferencias, paneles y medios",
    speakerLong: "Conferencias, paneles, formación in-company y medios",
    contact: "Escribime",
    pressKit: "Descargar press kit",
    work: "Cómo trabajar juntos",
    readMore: "Seguir leyendo",
    seeAll: "Ver todo",
    sendTelegram: "Enviar telegrama",
    watch: "Ver",
    filterAll: "Todos",
  },
  ui: {
    now: "Ahora",
    in: "En",
    based: "Basado en",
    next: "Próximo",
    featured: "Destacado en",
    selectedTalks: "Algunas charlas",
    selectedIdeas: "Ideas recientes",
    selectedPress: "Reconocimientos",
    fromUruguayTo: "De Uruguay al continente",
    languageShort: "ES",
    plate: "Placa",
    auto: "auto",
    paused: "pausa",
    currentlyWriting: "Escribiendo ahora",
    comingSoon: "Próximamente",
    chooseIntent: "Elegí una opción para continuar",
    yourName: "Tu nombre",
    organization: "Organización",
    context: "Contexto",
    yourEmail: "Tu email",
    replyBy: "Fecha límite de respuesta (opcional)",
    mailFallback: "¿No se abrió tu cliente de email? Copiá esto:",
  },
  home: {
    eyebrow: "IA aplicada · Estrategia · LATAM × Iberia",
    manifesto: { lead: "Hablo de IA", tail: "porque la construyo." },
    trip: {
      nowLabel: "Ahora",
      nextLabel: "Próximo",
      now: { city: "Santiago", country: "Chile", countryCode: "cl" },
      next: { city: "Lima", country: "Perú", countryCode: "pe", when: "2 ago · 1 semana" },
    },
    intro:
      "Soy Director de Innovación en Rocketbot. Lidero la evolución de producto agéntico, de IA aplicada y de eficiencia empresarial. He asesorado más de 200 clientes en siete países y fui seleccionado 40 Under 40 Innovators Global en 2024.",
    bioOneLine:
      "Constructor de producto agéntico. Escribo sobre IA aplicada al negocio en LATAM.",
    nowStatus:
      "Liderando el roadmap de agentes en Rocketbot. Escribiendo, en este espacio, sobre lo que voy aprendiendo mientras construyo IA aplicada.",
    stats: [
      { value: "200+", label: "Clientes asesorados" },
      { value: "7", label: "Países con ponencias" },
      { value: "3", label: "Premios globales 2016-18" },
      { value: "40<40", label: "Innovators 2024" },
    ],
    sections: [
      { number: "01", title: "Historia", blurb: "De Ciudad de la Costa al mundo. 11 capítulos.", href: "/historia" },
      { number: "02", title: "Qué hago", blurb: "Las áreas en las que trabajo y en las que más me metí.", href: "/que-hago" },
      { number: "03", title: "Charlas", blurb: "Keynotes, Agentic Tour y RPA Day.", href: "/charlas" },
      { number: "04", title: "Ideas", blurb: "Ensayos sin filtros sobre IA y negocio.", href: "/ideas" },
      { number: "05", title: "Posts", blurb: "Ideas cortas y animadas, para compartir.", href: "/posts" },
      { number: "06", title: "Prensa", blurb: "Premios y menciones en medios.", href: "/prensa" },
    ],
    quote: {
      text: "El 80% de los pilotos de IA que veo morir, mueren por mala estrategia, no por mala tecnología.",
      attribution: "Fernando Urbano, RPA Day España",
    },
    speakerPull: {
      eyebrow: "Booking & medios",
      title: "Si necesitas a alguien que hable de IA con hechos, no con humo.",
      blurb:
        "Keynotes, paneles, formación in-company, jurados de innovación, entrevistas en televisión, radio y podcast.",
    },
  },
  story: {
    eyebrow: "El recorrido",
    title: "11 capítulos. 29 años. Un solo recorrido.",
    intro:
      "No vengo de la teoría. Vengo de implementar, vender, romper, arreglar y volver a vender.",
    lead:
      "Nací en Ciudad de la Costa en 1997, hijo de Daniel y Mariela. La curiosidad fue el combustible desde el primer día.",
    stats: [
      { value: "11", label: "Capítulos" },
      { value: "6", label: "Empresas" },
      { value: "7", label: "Países" },
      { value: "1", label: "Obsesión" },
    ],
    chapters: storyChaptersEs,
    footerCta: { label: "Qué hago hoy", href: "/que-hago" },
  },
  services: {
    eyebrow: "En qué trabajo",
    title: "Producto agéntico, automatización e IA aplicada.",
    intro:
      "Trabajo en RPA, hiperautomatización, sistemas de IA, LLMs y agentes de negocio en LATAM e Iberia. Escribo de lo que construyo, no de lo que leo.",
    lanes: [
      {
        number: "01",
        title: "Producto agéntico",
        blurb:
          "Lidero el roadmap de agentes de negocio en Rocketbot: diseño, arquitectura y puesta en producción de sistemas que hacen trabajo real.",
        engagements: ["Agentes de negocio", "Multi-agente", "IA aplicada", "Roadmap de producto"],
        stat: { value: "2", label: "Años liderando agentes" },
      },
      {
        number: "02",
        title: "Automatización",
        blurb:
          "Más de una década en RPA e hiperautomatización: 80+ procesos automatizados en 12 países. De bots a agentes, con criterio de negocio.",
        engagements: ["RPA", "Hiperautomatización", "Orquestación", "Procesos"],
        stat: { value: "80+", label: "Procesos automatizados" },
      },
      {
        number: "03",
        title: "Criterio anti-bluff",
        blurb:
          "Separo lo que la IA va a hacer de lo que es humo. Hechos, casos y números; no promesas de LinkedIn. Es lo que trato de dejar por escrito acá.",
        engagements: ["Estrategia", "LLMs en producción", "Costo y latencia", "Riesgo"],
        stat: { value: "40<40", label: "Innovators Global 2024" },
      },
    ],
    expertiseTitle: "Espectro de expertise",
    expertiseIntro: "Profundidad acumulada por años en el terreno, no en slides.",
    expertise: [
      { id: "rpa", name: "RPA", level: 5, years: 8, caption: "80+ procesos automatizados en 12 países, Ricoh LATAM" },
      { id: "hyper", name: "Hiperautomatización", level: 5, years: 6, caption: "Practia / Publicis Sapient, banca y retail" },
      { id: "ai-sys", name: "Sistemas de IA", level: 4, years: 4, caption: "Arquitectura y despliegue en producción" },
      { id: "llm", name: "LLMs", level: 4, years: 3, caption: "Selección, costo, latencia y riesgo" },
      { id: "agents", name: "Agentes de negocio", level: 5, years: 2, caption: "Producto agéntico, Rocketbot" },
      { id: "multi", name: "Multi-agent systems", level: 4, years: 2, caption: "Roadmap agéntico global" },
    ],
    useCasesTitle: "Temas que me obsesionan",
    useCases: [
      { number: "01", title: "Portafolios de IA que se caen", blurb: "Qué cancelar, qué acelerar y qué medir de verdad." },
      { number: "02", title: "IA aplicada sin humo", blurb: "Lo que sí funciona en LATAM, con casos reales." },
      { number: "03", title: "Agentes en producción", blurb: "De piloto eterno a producción en 8 semanas." },
      { number: "04", title: "LLMs con criterio", blurb: "Costo, latencia y riesgo antes que hype." },
    ],
    ctaTalks: "Ver charlas",
    ctaContact: "Leer las ideas",
  },
  speaking: {
    eyebrow: "On Tour",
    title: "En vivo. 7 países. 1 mensaje.",
    intro:
      "Keynotes, webinars, capacitaciones y executive breakfasts. IA aplicada al negocio: lo que sí funciona, lo que no, y por qué.",
    stats: [
      { value: "10+", label: "Años en escenarios" },
      { value: "15+", label: "Ciudades" },
      { value: "7", label: "Países 2026" },
      { value: "1", label: "Mensaje" },
    ],
    agenticTour: {
      eyebrow: "Latest · 2026",
      title: "Agentic Tour 2026",
      blurb:
        "Capacitaciones, keynotes y executive breakfasts en siete países. El mensaje: agentes de negocio que entran a producción, no pilotos eternos.",
      stops: [
        { countryCode: "ar", city: "Buenos Aires", country: "Argentina", format: "Keynote + capacitación" },
        { countryCode: "cl", city: "Santiago", country: "Chile", format: "Executive breakfast" },
        { countryCode: "py", city: "Asunción", country: "Paraguay", format: "Capacitación" },
        { countryCode: "mx", city: "Ciudad de México", country: "México", format: "Keynote" },
        { countryCode: "co", city: "Bogotá", country: "Colombia", format: "Executive breakfast" },
        { countryCode: "pe", city: "Lima", country: "Perú", format: "Capacitación" },
        { countryCode: "uy", city: "Montevideo", country: "Uruguay", format: "Keynote" },
      ],
    },
    formats: [
      { name: "Keynote", description: "30 a 45 minutos. Conferencias y eventos masivos." },
      { name: "Panel", description: "60 a 90 minutos. Conversación con moderador." },
      { name: "Workshop", description: "Medio día a 3 días. In-company." },
      { name: "Executive breakfast", description: "90 minutos. C-level y boards." },
      { name: "Webinar", description: "60 minutos. Audiencia regional en vivo." },
    ],
    topics: [
      "IA aplicada al negocio en LATAM",
      "Agentes de negocio: arquitectura mínima viable",
      "Por qué los pilotos de IA mueren en producción",
      "RPA e hiperautomatización: de 80 procesos a agentes",
      "LLMs en producción: costo, latencia y riesgo",
      "Anti-bluff: evaluar una iniciativa de IA en 20 minutos",
    ],
    filterLabels: {
      all: "Todos",
      Keynote: "Keynote",
      Panel: "Panel",
      Workshop: "Workshop",
      "Charla magistral": "Charla",
      "Desayuno corporativo": "Breakfast",
      Webinar: "Webinar",
      Capacitacion: "Capacitación",
    },
    events: [
      {
        year: "2026",
        title: "Agentic Tour · Uruguay",
        venue: "Agentic Tour 2026",
        city: "Montevideo",
        country: "Uruguay",
        countryCode: "uy",
        format: "Keynote",
        featured: true,
      },
      {
        year: "2026",
        title: "Agentic Tour · Chile",
        venue: "Agentic Tour 2026",
        city: "Santiago",
        country: "Chile",
        countryCode: "cl",
        format: "Desayuno corporativo",
        featured: true,
      },
      {
        year: "2026",
        title: "Agentic Tour · Argentina",
        venue: "Agentic Tour 2026",
        city: "Buenos Aires",
        country: "Argentina",
        countryCode: "ar",
        format: "Keynote",
        featured: true,
      },
      {
        year: "2026",
        title: "Agentic Tour · México",
        venue: "Agentic Tour 2026",
        city: "Ciudad de México",
        country: "México",
        countryCode: "mx",
        format: "Keynote",
        featured: true,
      },
      {
        year: "2026",
        title: "Agentic Tour · Colombia",
        venue: "Agentic Tour 2026",
        city: "Bogotá",
        country: "Colombia",
        countryCode: "co",
        format: "Desayuno corporativo",
        featured: true,
      },
      {
        year: "2026",
        title: "Agentic Tour · Perú",
        venue: "Agentic Tour 2026",
        city: "Lima",
        country: "Perú",
        countryCode: "pe",
        format: "Capacitacion",
        featured: true,
      },
      {
        year: "2026",
        title: "Agentic Tour · Paraguay",
        venue: "Agentic Tour 2026",
        city: "Asunción",
        country: "Paraguay",
        countryCode: "py",
        format: "Capacitacion",
        featured: true,
      },
      {
        year: "2025",
        title: "Webinar oficial · Desarrollo de agentes de IA",
        venue: "Rocketbot",
        city: "Regional",
        country: "LATAM",
        countryCode: "world",
        format: "Webinar",
        featured: true,
      },
      {
        year: "2025",
        title: "RPA Day España",
        venue: "RPA Day",
        city: "Madrid",
        country: "España",
        countryCode: "es",
        format: "Keynote",
        featured: true,
      },
      {
        year: "2024",
        title: "Charla magistral · ORT",
        venue: "Universidad ORT",
        city: "Montevideo",
        country: "Uruguay",
        countryCode: "uy",
        format: "Charla magistral",
      },
      {
        year: "2023",
        title: "Palestra · UnoChapecó",
        venue: "UnoChapecó",
        city: "Chapecó",
        country: "Brasil",
        countryCode: "br",
        format: "Charla magistral",
      },
    ],
  },
  ideas: {
    eyebrow: "Ideas",
    title: "Lo que pienso, sin filtros.",
    intro:
      "Ensayos, takes y casos. Si solo vas a leer una cosa esta semana, que sea algo que cambie cómo decides el lunes.",
    currentlyWriting: {
      title: "Multi-agent systems en producción",
      status: "Borrador en curso",
      eta: "Jun 2026",
    },
    newsletter: {
      label: "Una idea por semana, sin spam",
      href: "mailto:fernando.urbano@rocketbot.com?subject=Newsletter",
    },
    pillars: [
      {
        number: "01",
        volume: "01",
        issue: "01",
        kicker: "Estrategia",
        title: "Lo que la IA SÍ va a hacer en LATAM (y lo que es humo)",
        lead: "Cinco cosas en las que sí vale la pena invertir capital. Tres que te van a hacer perderlo.",
        blurb:
          "Con ejemplos reales de los últimos 18 meses en banca, retail y telcos.",
        readingTime: "11 min",
        tags: ["LATAM", "Estrategia", "Capital"],
        slug: "ia-en-latam-y-lo-que-es-humo",
      },
      {
        number: "02",
        volume: "01",
        issue: "02",
        kicker: "Operaciones",
        title: "Por qué el 80% de los pilotos de IA mueren en producción",
        lead: "Una autopsia honesta. Spoiler: casi nunca es el modelo.",
        blurb: "Casi siempre es el proceso, el dato sucio y la falta de owner.",
        readingTime: "9 min",
        tags: ["Producción", "RPA", "Proceso"],
        slug: "por-que-mueren-los-pilotos-de-ia",
      },
      {
        number: "03",
        volume: "01",
        issue: "03",
        kicker: "Arquitectura",
        title: "Agentes que sí venden: arquitectura mínima viable",
        lead: "Ocho semanas a producción. Stack, decisiones y trade-offs.",
        blurb: "Cómo armar un agente de negocio que se pague solo.",
        readingTime: "14 min",
        tags: ["Agentes", "Arquitectura", "MVP"],
        slug: "agentes-que-si-venden-arquitectura-minima-viable",
      },
    ],
  },
  press: {
    eyebrow: "Reconocimiento",
    title: "4 premios. 12 años. Y una conversación que recién empieza.",
    intro:
      "Premios de innovación, menciones en medios y presencia en las redes de las marcas que mueven la automatización en LATAM.",
    awards: [
      {
        year: "2016",
        outlet: "24 Horas de Innovación",
        title: "Premio global de innovación",
        description:
          "Primer reconocimiento internacional por proyecto de innovación aplicada. El trabajo cruzó océanos antes que yo.",
      },
      {
        year: "2017",
        outlet: "Rally de Innovación",
        title: "Segundo premio consecutivo",
        description:
          "Confirmación de que no fue suerte: dos años seguidos siendo seleccionado entre proyectos globales.",
      },
      {
        year: "2018",
        outlet: "CampusParty",
        title: "Tercer premio global consecutivo",
        description:
          "CampusParty como escenario. Tres años seguidos de reconocimiento internacional en innovación.",
      },
      {
        year: "2024",
        outlet: "40 Under 40 Innovators Global",
        title: "Selección global",
        description:
          "Menos de 40 personas en el mundo por aporte a innovación aplicada. El recorrido confirmado fuera de la región.",
      },
    ],
    mentionsTitle: "Menciones en medios y redes",
    mentionsIntro:
      "Videos y apariciones en cuentas oficiales de marcas referentes en automatización, 2025-2026.",
    mentions: [
      {
        year: "2026",
        outlet: "Rocketbot Official",
        title: "Agentic Tour 2026 · highlights",
        kind: "social",
        thumbnailSrc: "/mentions/placeholders/01.svg",
      },
      {
        year: "2025",
        outlet: "Rocketbot Official",
        title: "Webinar agentes de IA · regional",
        kind: "social",
        thumbnailSrc: "/mentions/placeholders/02.svg",
      },
      {
        year: "2025",
        outlet: "RPA Day España",
        title: "Keynote RPA Day 2025",
        kind: "social",
        thumbnailSrc: "/mentions/placeholders/03.svg",
      },
      {
        year: "2025",
        outlet: "UiPath Community LATAM",
        title: "Mención comunidad RPA",
        kind: "social",
        thumbnailSrc: "/mentions/placeholders/04.svg",
      },
    ],
    pressKitBlurb:
      "Bio corta, media y larga en español e inglés, retratos editoriales, lista de temas, formatos y credenciales. Descarga directa en PDF.",
  },
  contact: {
    eyebrow: "Contacto",
    title: "¿Tenés algo para contarme? Escribime.",
    intro:
      "Leo todo. Si querés comentar una idea, discutir algo que escribí o simplemente saludar, el correo es el mejor canal.",
    intents: [
      {
        id: "keynote",
        label: "Keynote o panel",
        helper: "Conferencia, congreso, evento privado.",
        placeholder: "Audiencia estimada, formato, fecha tentativa, ciudad y tema que te interesa.",
        emailSubject: "Consulta keynote / panel",
      },
      {
        id: "advisory",
        label: "Asesoría",
        helper: "Board advisor, comité, sesión estratégica.",
        placeholder: "Empresa, rol que buscás, horizonte temporal y el problema concreto.",
        emailSubject: "Consulta asesoría",
      },
      {
        id: "training",
        label: "Formación in-company",
        helper: "Workshop ejecutivo o técnico.",
        placeholder: "Tamaño del equipo, nivel técnico, duración deseada y objetivo del workshop.",
        emailSubject: "Consulta formación in-company",
      },
      {
        id: "media",
        label: "Medios",
        helper: "Entrevista, columna, podcast, TV o radio.",
        placeholder: "Medio, formato, audiencia y fecha de publicación o grabación.",
        emailSubject: "Consulta medios",
      },
    ],
    form: {
      submit: "Enviar telegrama",
      nameLabel: "Tu nombre",
      orgLabel: "Organización",
      contextLabel: "Contexto",
      emailLabel: "Tu email",
      deadlineLabel: "Fecha límite de respuesta (opcional)",
    },
    methods: [
      { kind: "Email", label: "Email directo", value: "fernando.urbano@rocketbot.com", href: "mailto:fernando.urbano@rocketbot.com" },
      { kind: "LinkedIn", label: "LinkedIn", value: "/in/f-urcastro", href: "https://www.linkedin.com/in/f-urcastro/" },
    ],
  },
  footer: {
    sloganLine1: "IA sin bluff.",
    sloganLine2: "Negocios con velocidad.",
    rights: "Todos los derechos reservados",
    ticker: [
      "Director de Innovación · Rocketbot",
      "40 Under 40 Innovators Global 2024",
      "200+ clientes asesorados",
      "RPA e hiperautomatización desde 2016",
      "Premios globales 2016 · 2017 · 2018",
      "Escribo sobre IA aplicada al negocio.",
    ],
  },
};
