import type { StoryChapter } from "./types";

const BW = (n: string) => `/story/${n}-bw.jpeg`;
const COLOR = (n: string) => `/story/${n}-color.jpeg`;

export const storyChaptersEs: StoryChapter[] = [
  {
    id: "1997",
    number: "01",
    year: "1997",
    title: "Curiosidad como herencia",
    tagline: "Nacimiento en Ciudad de la Costa",
    city: "Ciudad de la Costa",
    country: "Uruguay",
    countryCode: "uy",
    body: "Nací en 1997 en Ciudad de la Costa, hijo de Daniel y Mariela. Desde chico la curiosidad fue el motor: desarmar, preguntar, volver a armar. No era un niño prodigio — era un niño que no podía dejar de entender cómo funcionaban las cosas.",
    imageSrc: BW("01"),
    imageColorSrc: COLOR("01"),
    imageAlt: "Fernando Urbano, infancia en Ciudad de la Costa, 1997",
  },
  {
    id: "2012",
    number: "02",
    year: "2012",
    title: "A los 15 elegí informática",
    tagline: "ESI Buceo, Montevideo",
    city: "Montevideo",
    country: "Uruguay",
    countryCode: "uy",
    company: "ESI Buceo",
    body: "Con 15 años decidí estudiar informática en la ESI Buceo. No fue una moda: fue la primera vez que sentí que el código y el negocio podían vivir en el mismo lugar. Aprendí a programar antes de aprender a vender — y eso marcó todo lo que vino después.",
    imageSrc: BW("02"),
    imageColorSrc: COLOR("02"),
    imageAlt: "Adolescente programando, ESI Buceo, 2012",
  },
  {
    id: "2015",
    number: "03",
    year: "2015",
    title: "Bachiller + primer trabajo",
    tagline: "eLace Media Services",
    city: "Montevideo",
    country: "Uruguay",
    countryCode: "uy",
    company: "eLace Media Services",
    role: "Tecnico TI -> Lider de proyectos",
    body: "Me recibí de bachiller en informática y el mismo año entré a eLace Media Services como tecnico de soporte TI. Ascenso rapido a lider de proyectos de TI. Primera vez liderando equipos, plazos y clientes reales — no simulaciones.",
    imageSrc: BW("03"),
    imageColorSrc: COLOR("03"),
    imageAlt: "Primer rol profesional en tecnologia, Montevideo, 2015",
  },
  {
    id: "2017",
    number: "04",
    year: "2017",
    title: "Cloud para LATAM",
    tagline: "Ricoh Latin America",
    city: "Montevideo",
    country: "Uruguay",
    countryCode: "uy",
    company: "Ricoh Latin America",
    role: "Administrador de cloud services",
    body: "Pase a Ricoh Latin America como administrador de cloud services. Operaciones regionales, infraestructura distribuida, clientes corporativos en varios paises. Aprendi escala antes de aprender estrategia — y eso despues me sirvio para todo.",
    imageSrc: BW("04"),
    imageColorSrc: COLOR("04"),
    imageAlt: "Administrador cloud services, Ricoh LATAM, 2017",
  },
  {
    id: "2018",
    number: "05",
    year: "2018",
    title: "Primera jefatura. 80+ procesos en 12 paises",
    tagline: "Automatizacion regional",
    city: "Regional",
    country: "LATAM",
    countryCode: "uy",
    company: "Ricoh Latin America",
    role: "Jefe regional de automatizacion de procesos",
    body: "En 2018 llego mi primera jefatura: area regional de automatizacion de procesos. Automatizamos mas de 80 procesos con RPA en mas de 12 paises. Fue el momento en que entendi que la tecnologia sin operacion muere — y que la operacion sin vision no escala.",
    imageSrc: BW("05"),
    imageColorSrc: COLOR("05"),
    imageAlt: "Jefatura regional RPA, Ricoh, 2018",
  },
  {
    id: "2022",
    number: "06",
    year: "2022",
    title: "Practia. Delivery Manager Chile",
    tagline: "Consultoria de transformacion",
    city: "Santiago",
    country: "Chile",
    countryCode: "cl",
    company: "Practia (Publicis Sapient)",
    role: "Delivery Manager Chile",
    body: "En 2022 aterrice en Practia como Delivery Manager para Chile. Banca, retail, telcos — proyectos de automatizacion e IA con equipos distribuidos. La consultoria me enseno a traducir tecnologia en lenguaje de junta directiva.",
    imageSrc: BW("06"),
    imageColorSrc: COLOR("06"),
    imageAlt: "Delivery Manager, Practia Chile, 2022",
  },
  {
    id: "2023",
    number: "07",
    year: "2023",
    title: "Head of Engineering Chile",
    tagline: "Liderazgo tecnico a escala",
    city: "Santiago",
    country: "Chile",
    countryCode: "cl",
    company: "Practia (Publicis Sapient)",
    role: "Head of Engineering Chile",
    body: "En 2023 pase a Head of Engineering para Chile. Liderazgo de equipos de ingenieria implementando RPA, IA y transformacion digital. Aprendi lo que un PowerPoint nunca ensena: por que los proyectos de IA mueren, y como mantenerlos vivos.",
    imageSrc: BW("07"),
    imageColorSrc: COLOR("07"),
    imageAlt: "Head of Engineering, Practia Chile, 2023",
  },
  {
    id: "2024-arg",
    number: "08",
    year: "2024",
    title: "Head of Engineering Argentina. 500+ personas",
    tagline: "Operacion de escala",
    city: "Buenos Aires",
    country: "Argentina",
    countryCode: "ar",
    company: "Practia (Publicis Sapient)",
    role: "Head of Engineering Argentina",
    body: "El mismo ano asumi Head of Engineering para Argentina: una operacion de mas de 500 personas. Escala humana, complejidad politica, multiples clientes simultaneos. El rol mas exigente antes de cruzar el Atlantico.",
    imageSrc: BW("08"),
    imageColorSrc: COLOR("08"),
    imageAlt: "Head of Engineering Argentina, Practia, 2024",
  },
  {
    id: "2024-mad",
    number: "09",
    year: "2024",
    title: "Cruce el Atlantico. Rocketbot EMEA/APAC",
    tagline: "Madrid",
    city: "Madrid",
    country: "Espana",
    countryCode: "es",
    company: "Rocketbot",
    role: "Partner Manager Senior EMEA/APAC",
    body: "Viaje a Madrid y me incorpore a Rocketbot como Partner Manager Senior para EMEA/APAC. Comercial, alianzas, expansion internacional. Primera vez que mi trabajo tenia fronteras fuera de LATAM de forma permanente.",
    imageSrc: BW("09"),
    imageColorSrc: COLOR("09"),
    imageAlt: "Partner Manager Senior, Rocketbot Madrid, 2024",
  },
  {
    id: "2025",
    number: "10",
    year: "2025",
    title: "Head of Agentic AI",
    tagline: "Producto agéntico",
    city: "Madrid",
    country: "Global",
    countryCode: "es",
    company: "Rocketbot",
    role: "Head of Agentic AI",
    body: "En 2025 pase a Head of Agentic AI. Lidero la evolucion del producto hacia agentes de negocio: arquitectura, roadmap, seleccion de modelos, criterio de negocio. Construyo el roadmap que asesoro.",
    imageSrc: BW("10"),
    imageColorSrc: COLOR("10"),
    imageAlt: "Head of Agentic AI, Rocketbot, 2025",
  },
  {
    id: "2026",
    number: "11",
    year: "2026",
    title: "Global Head of Innovation",
    tagline: "La obsesion se volvio rol",
    city: "Global",
    country: "Internacional",
    countryCode: "world",
    company: "Rocketbot",
    role: "Global Head of Innovation",
    body: "En 2026 asumo como Global Head of Innovation. La curiosidad de 1997, el codigo de 2012, los 80 procesos de 2018 y el continente recorrido en charlas — todo converge en un solo rol: mover empresas con IA aplicada, sin bluff.",
    imageSrc: BW("11"),
    imageColorSrc: COLOR("11"),
    imageAlt: "Global Head of Innovation, Rocketbot, 2026",
  },
];

export const storyChaptersEn: StoryChapter[] = [
  {
    id: "1997",
    number: "01",
    year: "1997",
    title: "Curiosity as inheritance",
    tagline: "Born in Ciudad de la Costa",
    city: "Ciudad de la Costa",
    country: "Uruguay",
    countryCode: "uy",
    body: "Born in 1997 in Ciudad de la Costa, son of Daniel and Mariela. From childhood curiosity was the engine: take apart, ask, put back together. Not a prodigy — a kid who couldn't stop understanding how things work.",
    imageSrc: BW("01"),
    imageColorSrc: COLOR("01"),
    imageAlt: "Fernando Urbano, childhood in Ciudad de la Costa, 1997",
  },
  {
    id: "2012",
    number: "02",
    year: "2012",
    title: "At 15 I chose computer science",
    tagline: "ESI Buceo, Montevideo",
    city: "Montevideo",
    country: "Uruguay",
    countryCode: "uy",
    company: "ESI Buceo",
    body: "At 15 I decided to study computer science at ESI Buceo. Not a trend — the first time I felt code and business could live in the same place. I learned to program before I learned to sell — and that shaped everything that followed.",
    imageSrc: BW("02"),
    imageColorSrc: COLOR("02"),
    imageAlt: "Teenager programming, ESI Buceo, 2012",
  },
  {
    id: "2015",
    number: "03",
    year: "2015",
    title: "High school graduate + first job",
    tagline: "eLace Media Services",
    city: "Montevideo",
    country: "Uruguay",
    countryCode: "uy",
    company: "eLace Media Services",
    role: "IT support -> Project lead",
    body: "Graduated in computer science and the same year joined eLace Media Services as IT support technician. Quickly promoted to IT project lead. First time leading teams, deadlines and real clients — not simulations.",
    imageSrc: BW("03"),
    imageColorSrc: COLOR("03"),
    imageAlt: "First professional tech role, Montevideo, 2015",
  },
  {
    id: "2017",
    number: "04",
    year: "2017",
    title: "Cloud for LATAM",
    tagline: "Ricoh Latin America",
    city: "Montevideo",
    country: "Uruguay",
    countryCode: "uy",
    company: "Ricoh Latin America",
    role: "Cloud services administrator",
    body: "Moved to Ricoh Latin America as cloud services administrator. Regional operations, distributed infrastructure, corporate clients across countries. Learned scale before strategy — and that served me for everything after.",
    imageSrc: BW("04"),
    imageColorSrc: COLOR("04"),
    imageAlt: "Cloud services administrator, Ricoh LATAM, 2017",
  },
  {
    id: "2018",
    number: "05",
    year: "2018",
    title: "First leadership. 80+ processes in 12 countries",
    tagline: "Regional automation",
    city: "Regional",
    country: "LATAM",
    countryCode: "uy",
    company: "Ricoh Latin America",
    role: "Regional process automation lead",
    body: "In 2018 came my first leadership role: regional process automation area. We automated 80+ processes with RPA across 12+ countries. The moment I understood technology without operations dies — and operations without vision doesn't scale.",
    imageSrc: BW("05"),
    imageColorSrc: COLOR("05"),
    imageAlt: "Regional RPA leadership, Ricoh, 2018",
  },
  {
    id: "2022",
    number: "06",
    year: "2022",
    title: "Practia. Delivery Manager Chile",
    tagline: "Transformation consulting",
    city: "Santiago",
    country: "Chile",
    countryCode: "cl",
    company: "Practia (Publicis Sapient)",
    role: "Delivery Manager Chile",
    body: "In 2022 I landed at Practia as Delivery Manager for Chile. Banking, retail, telcos — automation and AI projects with distributed teams. Consulting taught me to translate technology into boardroom language.",
    imageSrc: BW("06"),
    imageColorSrc: COLOR("06"),
    imageAlt: "Delivery Manager, Practia Chile, 2022",
  },
  {
    id: "2023",
    number: "07",
    year: "2023",
    title: "Head of Engineering Chile",
    tagline: "Technical leadership at scale",
    city: "Santiago",
    country: "Chile",
    countryCode: "cl",
    company: "Practia (Publicis Sapient)",
    role: "Head of Engineering Chile",
    body: "In 2023 I became Head of Engineering for Chile. Leading engineering teams implementing RPA, AI and digital transformation. Learned what no slide teaches: why AI projects die, and how to keep them alive.",
    imageSrc: BW("07"),
    imageColorSrc: COLOR("07"),
    imageAlt: "Head of Engineering, Practia Chile, 2023",
  },
  {
    id: "2024-arg",
    number: "08",
    year: "2024",
    title: "Head of Engineering Argentina. 500+ people",
    tagline: "Scale operations",
    city: "Buenos Aires",
    country: "Argentina",
    countryCode: "ar",
    company: "Practia (Publicis Sapient)",
    role: "Head of Engineering Argentina",
    body: "Same year I took Head of Engineering for Argentina: an operation of 500+ people. Human scale, political complexity, multiple simultaneous clients. The most demanding role before crossing the Atlantic.",
    imageSrc: BW("08"),
    imageColorSrc: COLOR("08"),
    imageAlt: "Head of Engineering Argentina, Practia, 2024",
  },
  {
    id: "2024-mad",
    number: "09",
    year: "2024",
    title: "Crossed the Atlantic. Rocketbot EMEA/APAC",
    tagline: "Madrid",
    city: "Madrid",
    country: "Spain",
    countryCode: "es",
    company: "Rocketbot",
    role: "Senior Partner Manager EMEA/APAC",
    body: "Traveled to Madrid and joined Rocketbot as Senior Partner Manager for EMEA/APAC. Commercial, alliances, international expansion. First time my work had borders outside LATAM permanently.",
    imageSrc: BW("09"),
    imageColorSrc: COLOR("09"),
    imageAlt: "Senior Partner Manager, Rocketbot Madrid, 2024",
  },
  {
    id: "2025",
    number: "10",
    year: "2025",
    title: "Head of Agentic AI",
    tagline: "Agentic product",
    city: "Madrid",
    country: "Global",
    countryCode: "es",
    company: "Rocketbot",
    role: "Head of Agentic AI",
    body: "In 2025 I became Head of Agentic AI. I lead the product evolution toward business agents: architecture, roadmap, model selection, business judgment. I build the roadmap I advise on.",
    imageSrc: BW("10"),
    imageColorSrc: COLOR("10"),
    imageAlt: "Head of Agentic AI, Rocketbot, 2025",
  },
  {
    id: "2026",
    number: "11",
    year: "2026",
    title: "Global Head of Innovation",
    tagline: "The obsession became the role",
    city: "Global",
    country: "International",
    countryCode: "world",
    company: "Rocketbot",
    role: "Global Head of Innovation",
    body: "In 2026 I take on Global Head of Innovation. The curiosity of 1997, the code of 2012, the 80 processes of 2018 and the continent crossed in talks — all converge in one role: moving companies with applied AI, without bluff.",
    imageSrc: BW("11"),
    imageColorSrc: COLOR("11"),
    imageAlt: "Global Head of Innovation, Rocketbot, 2026",
  },
];
